import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const interRounded = LocalFont({
  variable: "--font-inter-rounded",
  src: [
    { path: "./fonts/OpenRunde-Semibold.woff2", weight: "500" }
  ]
});

export const metadata: Metadata = {
  title: "HenHacks2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${interRounded.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
